"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowRight, Eye, EyeOff, Home, LockKeyhole, Mail, Phone, ShoppingBag, User } from "lucide-react";
import { authClient } from "@/lib/auth-client";

export default function CustomerRegisterPage() {
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [address, setAddress] = useState(""); const [city, setCity] = useState("");
  const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (loading) return; setError("");
    if (password !== confirmPassword) { setError("Passwords do not match."); return; }
    if (password.length < 8) { setError("Your password must be at least 8 characters."); return; }
    setLoading(true);
    try {
      const result = await authClient.signUp.email({ name: name.trim(), email: email.trim(), password, phone: phone.trim() });
      if (result.error) { setError(result.error.message || "Unable to create your account."); return; }
      const addressResponse = await fetch("/api/account/addresses", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label: "Home", recipientName: name.trim(), phone: phone.trim(), address: address.trim(), city: city.trim(), isDefault: true }) });
      if (!addressResponse.ok) console.warn("Account created, but the initial address could not be saved.");
      window.location.replace("/account");
    } catch (registerError) { console.error("Customer registration failed:", registerError); setError("Something went wrong while creating your account. Please try again."); }
    finally { setLoading(false); }
  }

  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto flex min-h-screen w-full max-w-6xl items-center justify-center px-5 py-10 sm:px-8"><div className="grid w-full overflow-hidden rounded-[2rem] border border-border/70 bg-card shadow-2xl lg:grid-cols-[0.9fr_1.1fr]">
    <section className="hidden bg-primary p-10 text-primary-foreground lg:flex lg:flex-col lg:justify-between xl:p-14"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-accent text-[9px] font-black text-white">SST</div><div><p className="text-lg font-black">Sampath Food City</p><p className="text-[10px] uppercase tracking-[0.2em] text-primary-foreground/50">Customer account</p></div></div><div><ShoppingBag className="h-8 w-8 text-accent" /><h1 className="mt-6 text-5xl font-black leading-none tracking-tight">Shopping made<br /><span className="text-accent">simpler.</span></h1><p className="mt-6 max-w-md text-sm leading-7 text-primary-foreground/65">Create your account to save delivery details, follow orders and quickly reorder from Sampath Food City.</p></div><p className="text-xs text-primary-foreground/35">Sampath Food City · Customer account</p></section>
    <section className="p-6 sm:p-10 lg:p-12"><div className="mb-8 lg:hidden"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-accent text-[9px] font-black text-white">SST</div></div><p className="text-xs font-bold uppercase tracking-[0.16em] text-accent">Create account</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Welcome to SST</h2><p className="mt-2 text-sm text-muted-foreground">Save your details and keep every order in one place.</p>
      <form onSubmit={handleSubmit} className="mt-8 space-y-5"><Field icon={<User className="h-4 w-4" />} label="Full name"><input required autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Your full name" className="field-input" /></Field><div className="grid gap-5 sm:grid-cols-2"><Field icon={<Phone className="h-4 w-4" />} label="Phone number"><input required type="tel" autoComplete="tel" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="07X XXX XXXX" className="field-input" /></Field><Field icon={<Mail className="h-4 w-4" />} label="Email address"><input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" className="field-input" /></Field></div><Field icon={<Home className="h-4 w-4" />} label="Delivery address"><textarea required autoComplete="street-address" value={address} onChange={(e) => setAddress(e.target.value)} rows={2} placeholder="House number, street, landmark" className="field-input h-auto py-3" /></Field><Field icon={<Home className="h-4 w-4" />} label="City / area"><input required autoComplete="address-level2" value={city} onChange={(e) => setCity(e.target.value)} placeholder="City or area" className="field-input" /></Field><Field icon={<LockKeyhole className="h-4 w-4" />} label="Password"><div className="relative"><input required minLength={8} type={showPassword ? "text" : "password"} autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 8 characters" className="field-input pr-12" /><button type="button" onClick={() => setShowPassword((v) => !v)} className="absolute right-2 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-lg text-muted-foreground hover:bg-muted" aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></Field><Field icon={<LockKeyhole className="h-4 w-4" />} label="Confirm password"><input required minLength={8} type={showPassword ? "text" : "password"} autoComplete="new-password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Re-enter your password" className="field-input" /></Field>{error && <div role="alert" className="rounded-xl border border-destructive/20 bg-destructive/10 px-4 py-3 text-xs font-medium leading-5 text-destructive">{error}</div>}<button type="submit" disabled={loading} className="group flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-accent text-sm font-bold text-accent-foreground shadow-lg shadow-accent/20 transition-all hover:-translate-y-0.5 disabled:cursor-wait disabled:opacity-60">{loading ? "Creating account..." : <>Create account<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></>}</button></form>
      <p className="mt-7 text-center text-sm text-muted-foreground">Already have an account? <Link href="/account/login" className="font-bold text-accent hover:underline">Sign in</Link></p><p className="mt-4 text-center text-xs text-muted-foreground"><Link href="/" className="hover:text-foreground">← Back to shopping</Link></p>
    </section></div></div><style jsx global>{`.field-input{min-height:3rem;width:100%;border-radius:.75rem;border:1px solid hsl(var(--border));background:hsl(var(--background));padding:0 1rem;font-size:.875rem;outline:none;transition:all .2s}.field-input:focus{border-color:hsl(var(--accent));box-shadow:0 0 0 4px hsl(var(--accent)/.1)}`}</style></main>;
}
function Field({ icon, label, children }: { icon: React.ReactNode; label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-semibold"><span className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{icon}{label}</span>{children}</label>; }
