"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Check, Clock3, MapPin, Package, RefreshCw, ShoppingBag, Truck, XCircle } from "lucide-react";

type Order = { id: string; orderNumber: string; status: string; paymentStatus: string; subtotal: number; deliveryFee: number; total: number; deliveryLatitude: number; deliveryLongitude: number; deliveryDistanceKm: number; customerName: string; customerPhone: string; notes: string | null; createdAt: string; updatedAt: string; branch: { name: string; code: string }; items: { id: string; quantity: number; unitPrice: number; total: number; product: { name: string; imageUrl: string | null; sku: string } }[] };
const steps = ["PENDING", "CONFIRMED", "PREPARING", "OUT_FOR_DELIVERY", "DELIVERED"];
const labels: Record<string, string> = { PENDING: "Order received", ASSIGNED: "Rider assigned", CONFIRMED: "Confirmed", PREPARING: "Preparing", READY_FOR_PICKUP: "Ready for pickup", OUT_FOR_DELIVERY: "Out for delivery", DELIVERED: "Delivered", CANCELLED: "Cancelled" };

export default function CustomerOrderPage() {
  const [order, setOrder] = useState<Order | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const response = await fetch(`/api/account/orders/${window.location.pathname.split("/").pop()}`, { cache: "no-store" }); const data = await response.json(); if (response.status === 401) { window.location.replace("/account/login"); return; } if (!response.ok) throw new Error(data.error || "Unable to load this order."); setOrder(data); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load this order."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  if (loading) return <main className="min-h-screen bg-background px-4 py-16"><div className="mx-auto max-w-3xl space-y-4"><div className="h-10 w-48 animate-pulse rounded-xl bg-muted" /><div className="h-96 animate-pulse rounded-[2rem] bg-muted" /></div></main>;
  if (error || !order) return <main className="min-h-screen bg-background px-4 py-16"><div className="mx-auto max-w-xl rounded-[2rem] border border-border bg-card p-10 text-center"><XCircle className="mx-auto h-10 w-10 text-destructive" /><h1 className="mt-5 text-2xl font-black">Unable to load order</h1><p className="mt-2 text-sm text-muted-foreground">{error || "This order could not be found."}</p><Link href="/account" className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-accent px-5 text-sm font-bold text-accent-foreground"><ArrowLeft className="h-4 w-4" />Back to account</Link></div></main>;
  const cancelled = order.status === "CANCELLED"; const currentStep = steps.indexOf(order.status); const deliveryAddress = (order.notes ?? "").split("\n");
  return <main className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-4xl items-center px-4 sm:px-6"><Link href="/account" className="group flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />My account</Link><button onClick={() => void load()} className="ml-auto flex h-9 w-9 items-center justify-center rounded-xl border border-border text-muted-foreground hover:bg-muted" aria-label="Refresh order"><RefreshCw className="h-4 w-4" /></button></div></header>
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-accent">Order tracking</p><h1 className="mt-2 text-3xl font-black tracking-tight">{order.orderNumber}</h1><p className="mt-2 text-sm text-muted-foreground">Placed {new Date(order.createdAt).toLocaleString("en-LK", { dateStyle: "medium", timeStyle: "short" })} · {order.branch.name}</p></div><span className="rounded-full bg-accent/10 px-3 py-1.5 text-xs font-bold text-accent">{labels[order.status] ?? order.status}</span></div>
      <section className="mt-8 rounded-[2rem] border border-border/70 bg-card p-5 shadow-sm sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Live progress</p><h2 className="mt-1 text-lg font-black">Your order status</h2></div><Truck className="h-6 w-6 text-accent" /></div>{cancelled ? <div className="mt-6 rounded-2xl border border-destructive/20 bg-destructive/10 p-5"><p className="font-black text-destructive">This order was cancelled.</p><p className="mt-1 text-xs text-muted-foreground">Please contact the branch if you need more information.</p></div> : <div className="mt-8 grid grid-cols-5 gap-1">{steps.map((step, index) => { const active = index <= currentStep; return <div key={step} className="relative text-center"><div className={`mx-auto flex h-10 w-10 items-center justify-center rounded-full border ${active ? "border-accent bg-accent text-accent-foreground" : "border-border bg-muted text-muted-foreground"}`}>{index === 0 ? <Clock3 className="h-4 w-4" /> : index === 1 ? <Check className="h-4 w-4" /> : index === 2 ? <Package className="h-4 w-4" /> : index === 3 ? <Truck className="h-4 w-4" /> : <Check className="h-4 w-4" />}</div><p className={`mt-2 text-[10px] font-bold leading-4 ${active ? "text-foreground" : "text-muted-foreground"}`}>{labels[step]}</p>{index < steps.length - 1 && <span className={`absolute left-[calc(50%+20px)] right-[calc(-50%+20px)] top-5 h-px ${index < currentStep ? "bg-accent" : "bg-border"}`} />}</div> })}</div>}{order.status === "DELIVERED" && <div className="mt-6 rounded-2xl border border-accent/20 bg-accent/5 p-4 text-sm font-semibold text-accent">Your order has been delivered. Thank you for shopping with Sampath Food City!</div>}</section>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_330px]"><section className="rounded-[2rem] border border-border/70 bg-card p-5 shadow-sm sm:p-7"><h2 className="text-lg font-black">Items</h2><div className="mt-5 space-y-3">{order.items.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-border bg-background p-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-muted">{item.product.imageUrl ? <img src={item.product.imageUrl} alt={item.product.name} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><ShoppingBag className="h-5 w-5 text-muted-foreground/40" /></div>}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold">{item.product.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.quantity} × Rs. {item.unitPrice.toLocaleString()}</p></div><p className="text-sm font-black">Rs. {item.total.toLocaleString()}</p></div>)}</div></section>
        <aside className="h-fit rounded-[2rem] border border-border/70 bg-card p-5 shadow-sm sm:p-7"><h2 className="text-lg font-black">Order summary</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span className="font-semibold">Rs. {order.subtotal.toLocaleString()}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Delivery</span><span className="font-semibold">Rs. {order.deliveryFee.toLocaleString()}</span></div><div className="h-px bg-border" /><div className="flex justify-between text-base"><span className="font-bold">Total</span><span className="font-black">Rs. {order.total.toLocaleString()}</span></div></div><div className="mt-6 rounded-2xl border border-border bg-background p-4"><div className="flex gap-3"><MapPin className="h-4 w-4 shrink-0 text-accent" /><div><p className="text-xs font-bold">Delivery details</p><p className="mt-1 text-xs font-semibold">{order.customerName}</p><p className="text-xs text-muted-foreground">{deliveryAddress[0]}</p><p className="text-xs text-muted-foreground">{deliveryAddress[1]}</p><p className="mt-1 text-xs text-muted-foreground">{order.customerPhone}</p></div></div></div><div className="mt-4 rounded-2xl bg-muted/50 p-4"><p className="text-xs font-bold">Payment</p><p className="mt-1 text-xs text-muted-foreground">Cash on Delivery · {order.paymentStatus}</p></div></aside></div>
    </div></main>;
}
